config/routes.rb
Apptemp::Application.routes.draw do
  resources :sub_pages
  resources :pages

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root :to => "home#index"

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= begin
	    extname = File.extname(filename).gsub(/^\./, '')
      "/javascripts/ckeditor/filebrowser/images/thumbs/#{extname}.gif"
	  end
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :sub_pages
end

app/models/sub_page.rb
class SubPage < ActiveRecord::Base
  belongs_to :page
  
  def to_param
    self.browser_title.blank? ? "#{self.title.parameterize}" : "#{self.browser_title.parameterize}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sub_pages_controller.rb
class SubPagesController < ApplicationController
  # GET /sub_pages
  # GET /sub_pages.json
  def index
    @sub_pages = SubPage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sub_pages }
    end
  end

  # GET /sub_pages/1
  # GET /sub_pages/1.json
  def show
    @sub_page = SubPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub_page }
    end
  end

  # GET /sub_pages/new
  # GET /sub_pages/new.json
  def new
    @sub_page = SubPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub_page }
    end
  end

  # GET /sub_pages/1/edit
  def edit
    @sub_page = SubPage.find(params[:id])
  end

  # POST /sub_pages
  # POST /sub_pages.json
  def create
    @sub_page = SubPage.new(params[:sub_page])

    respond_to do |format|
      if @sub_page.save
        format.html { redirect_to @sub_page, notice: 'Sub page was successfully created.' }
        format.json { render json: @sub_page, status: :created, location: @sub_page }
      else
        format.html { render action: "new" }
        format.json { render json: @sub_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sub_pages/1
  # PUT /sub_pages/1.json
  def update
    @sub_page = SubPage.find(params[:id])

    respond_to do |format|
      if @sub_page.update_attributes(params[:sub_page])
        format.html { redirect_to @sub_page, notice: 'Sub page was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_pages/1
  # DELETE /sub_pages/1.json
  def destroy
    @sub_page = SubPage.find(params[:id])
    @sub_page.destroy

    respond_to do |format|
      format.html { redirect_to sub_pages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sub_pages_helper.rb
module SubPagesHelper
end

app/views/home/index.html.erb
Hello!

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => key }
      %p= value

app/views/layouts/_footer.html.haml
%small.copyright
  Copyright &copy; #{Date.today.year}

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title
  == #{ controller.controller_name.titleize } - #{ controller.action_name.titleize }
  
%meta{ :name => "description", :content => "" }/
%meta{ :name => "author", :content => "" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/

-# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

-# Pass in a stylesheet_partial to render inside your head
- if local_assigns[:stylesheet_partial]
  = render :partial => local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr and Respond.
-# Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
= javascript_include_tag 'modernizr.min', 'respond.min'

= csrf_meta_tag

app/views/layouts/_header.html.haml
%h1 Header

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery, with a protocol relative URL
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
-# remote_jquery and local_jquery helpers use minified jquery unless Rails.env is development
- if !google_api_key.blank?
  = javascript_include_tag "//www.google.com/jsapi?key=#{google_api_key}"
  :javascript
    google.load(#{ remote_jquery("1.6") });
- else
  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/#{ local_jquery("1.6") }"

-# fall back to local jQuery if necessary
:javascript
  window.jQuery || document.write("<script src='/javascripts/jquery.min.js'>\x3C/script>")
  
= javascript_include_tag 'application'
    
-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[["_setAccount","#{google_account_id}"],["_trackPageview"],["_trackPageLoadTime"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));

app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'style', :media => 'all'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    -# To render a different stylesheet partial inside the head (i.e. for admin layout)
    -# just copy _stylesheets.html.haml, and point to that partial instead.
    = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"
  
  %body{ :class => "#{controller.controller_name}" }
    #container
      %header#header
        = render "layouts/header"
        
      #main{ :role => 'main' }
        = render "layouts/flashes"
        = yield
        
      %footer#footer
        = render "layouts/footer"
        
    -# Javascript at the bottom for fast page loading
    = render "layouts/javascripts"

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :browser_title %><br />
    <%= f.text_field :browser_title %>
  </div>
  <div class="field">
    <%= f.label :meta_keywords %><br />
    <%= f.text_field :meta_keywords %>
  </div>
  <div class="field">
    <%= f.label :meta_description %><br />
    <%= f.text_field :meta_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Browser title</th>
    <th>Meta keywords</th>
    <th>Meta description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.content %></td>
    <td><%= page.browser_title %></td>
    <td><%= page.meta_keywords %></td>
    <td><%= page.meta_description %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>

<p>
  <b>Browser title:</b>
  <%= @page.browser_title %>
</p>

<p>
  <b>Meta keywords:</b>
  <%= @page.meta_keywords %>
</p>

<p>
  <b>Meta description:</b>
  <%= @page.meta_description %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/sub_pages/_form.html.erb
<%= form_for(@sub_page) do |f| %>
  <% if @sub_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_page.errors.count, "error") %> prohibited this sub_page from being saved:</h2>

      <ul>
      <% @sub_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page_id %><br />
    <%= f.number_field :page_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :browser_title %><br />
    <%= f.text_field :browser_title %>
  </div>
  <div class="field">
    <%= f.label :meta_keywords %><br />
    <%= f.text_field :meta_keywords %>
  </div>
  <div class="field">
    <%= f.label :meta_description %><br />
    <%= f.text_field :meta_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_pages/edit.html.erb
<h1>Editing sub_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_page %> |
<%= link_to 'Back', sub_pages_path %>

app/views/sub_pages/index.html.erb
<h1>Listing sub_pages</h1>

<table>
  <tr>
    <th>Page</th>
    <th>Title</th>
    <th>Content</th>
    <th>Browser title</th>
    <th>Meta keywords</th>
    <th>Meta description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sub_pages.each do |sub_page| %>
  <tr>
    <td><%= sub_page.page_id %></td>
    <td><%= sub_page.title %></td>
    <td><%= sub_page.content %></td>
    <td><%= sub_page.browser_title %></td>
    <td><%= sub_page.meta_keywords %></td>
    <td><%= sub_page.meta_description %></td>
    <td><%= link_to 'Show', sub_page %></td>
    <td><%= link_to 'Edit', edit_sub_page_path(sub_page) %></td>
    <td><%= link_to 'Destroy', sub_page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sub page', new_sub_page_path %>

app/views/sub_pages/new.html.erb
<h1>New sub_page</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_pages_path %>

app/views/sub_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Page:</b>
  <%= @sub_page.page_id %>
</p>

<p>
  <b>Title:</b>
  <%= @sub_page.title %>
</p>

<p>
  <b>Content:</b>
  <%= @sub_page.content %>
</p>

<p>
  <b>Browser title:</b>
  <%= @sub_page.browser_title %>
</p>

<p>
  <b>Meta keywords:</b>
  <%= @sub_page.meta_keywords %>
</p>

<p>
  <b>Meta description:</b>
  <%= @sub_page.meta_description %>
</p>


<%= link_to 'Edit', edit_sub_page_path(@sub_page) %> |
<%= link_to 'Back', sub_pages_path %>